---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-apis
  namespace: flux-system
spec:
  interval: 5m
  path: ./apis/v1alpha1
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-configs
  healthChecks:
  - apiVersion: apiextensions.crossplane.io/v2
    kind: CompositeResourceDefinition
    name: xpostgresqldatabases.database.example.io
